import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import ".././globals.css";
import React from "react";
import Leftsidebar from "@/components/Leftsidebar";
import Rightsidebar from "@/components/Rightsidebar";
import { ClerkProvider ,ClerkLoading,ClerkLoaded} from "@clerk/nextjs";
import Loading from "@/components/Loading";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <ClerkProvider>
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ClerkLoading>
          <Loading/>
        </ClerkLoading>
        <ClerkLoaded>
        <div className="flex min-h-screen">
          {/* Left Sidebar */}
          <div className="w-1/5 relative">

            <Leftsidebar />
            {/* Gradient divider to the right */}
            <div className="absolute right-0 top-0 h-full w-[3px] bg-gradient-to-b from-pink-500 via-purple-500 to-blue-500"></div>
          </div>

          {/* Home / Main Content */}
          <div className="flex-1 relative">
            <main className="flex flex-col items-center justify-center p-8 text-center">
              {children}
            </main>
            {/* Gradient divider to the right */}
            <div className="absolute right-0 top-0 h-full w-[3px] bg-gradient-to-b from-green-400 via-yellow-400 to-red-400"></div>
          </div>

          {/* Right Sidebar */}
          
          <div className="w-[30%]">
            <Rightsidebar />
          </div>
          
        </div>
        </ClerkLoaded>
      </body>
    </html>
    </ClerkProvider>
  );
}
